/**
 * squad build — compile TypeScript squad definitions into .squad/ markdown.
 *
 * Loads squad.config.ts (or squad/index.ts) and generates:
 *   - .squad/team.md
 *   - .squad/routing.md
 *   - .squad/agents/{name}/charter.md
 *   - .squad/ceremonies.md
 *
 * NEVER touches: decisions.md, history.md, orchestration-log/
 *
 * Flags:
 *   --check    validate without writing (exit 0 if matches disk, exit 1 if drift)
 *   --dry-run  show what would be generated without writing
 *   --watch    rebuild on .ts file changes (stub for now)
 *
 * @module cli/commands/build
 */

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { success, warn, info, dim, BOLD, RESET, YELLOW, GREEN, RED } from '../core/output.js';
import { fatal } from '../core/errors.js';

import type {
  SquadSDKConfig,
  AgentDefinition,
  CeremonyDefinition,
  ModelPreference,
  BuilderModelId,
} from '@bradygaster/squad-sdk';
import type { SkillDefinition as BuilderSkillDefinition } from '@bradygaster/squad-sdk/builders';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATED_HEADER = '<!-- generated by squad build — do not edit -->\n\n';

/** Files we must NEVER overwrite. */
const PROTECTED_FILES = new Set([
  'decisions.md',
  'decisions-archive.md',
]);

/** Directory prefixes we must NEVER touch. */
const PROTECTED_DIRS = new Set([
  'orchestration-log',
]);

// ---------------------------------------------------------------------------
// Config loading
// ---------------------------------------------------------------------------

interface LoadedConfig {
  config: SquadSDKConfig;
  source: string;
}

/**
 * Discover and dynamically import the squad config file.
 * Search order:
 *   1. squad/index.ts
 *   2. squad.config.ts
 *   3. squad.config.js
 */
async function loadSquadConfig(cwd: string): Promise<LoadedConfig> {
  const candidates = [
    path.join(cwd, 'squad', 'index.ts'),
    path.join(cwd, 'squad.config.ts'),
    path.join(cwd, 'squad.config.js'),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      try {
        const url = pathToFileURL(candidate).href;
        const mod = await import(url);
        const config: SquadSDKConfig = mod.default ?? mod.config ?? mod.squadConfig;
        if (!config) {
          fatal(`${candidate} must export default, "config", or "squadConfig"`);
        }
        return { config, source: candidate };
      } catch (err) {
        fatal(`Failed to load ${candidate}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
  }

  fatal(
    'No squad config found. Create squad.config.ts or squad/index.ts\n' +
    '       Run "squad init" to bootstrap a new project.',
  );
}

// ---------------------------------------------------------------------------
// Markdown generators
// ---------------------------------------------------------------------------

function generateTeamMd(config: SquadSDKConfig): string {
  const lines: string[] = [GENERATED_HEADER];
  const teamName = config.team.name;
  const desc = config.team.description ?? '';

  lines.push(`# Squad Team — ${teamName}\n`);
  if (desc) {
    lines.push(`> ${desc}\n`);
  }

  // Coordinator row
  lines.push('## Coordinator\n');
  lines.push('| Name | Role | Notes |');
  lines.push('|------|------|-------|');
  lines.push('| Squad | Coordinator | Routes work, enforces handoffs and reviewer gates. Does not generate domain artifacts. |');
  lines.push('');

  // Members table
  const agents = config.agents;
  if (agents.length > 0) {
    lines.push('## Members\n');
    lines.push('| Name | Role | Charter | Status |');
    lines.push('|------|------|---------|--------|');
    for (const agent of agents) {
      const name = capitalize(agent.name);
      const role = agent.role;
      const charter = `.squad/agents/${agent.name}/charter.md`;
      const status = formatStatus(agent.status);
      lines.push(`| ${name} | ${role} | \`${charter}\` | ${status} |`);
    }
    lines.push('');
  }

  // Project context
  if (config.team.projectContext) {
    lines.push('## Project Context\n');
    lines.push(config.team.projectContext);
    lines.push('');
  }

  return lines.join('\n');
}

function generateRoutingMd(config: SquadSDKConfig): string {
  if (!config.routing) return '';
  const lines: string[] = [GENERATED_HEADER];
  const teamName = config.team.name;

  lines.push(`# Routing Rules — ${teamName}\n`);

  if (config.routing.defaultAgent) {
    lines.push(`**Default agent:** ${config.routing.defaultAgent}\n`);
  }

  lines.push('## Rules\n');

  const rules = config.routing.rules;
  for (const rule of rules) {
    const agents = rule.agents.join(', ');
    const desc = rule.description ? ` — ${rule.description}` : '';
    lines.push(`- \`${rule.pattern}\` → ${agents}${desc}`);
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Normalize a model field (string or ModelPreference) into a ModelPreference object.
 */
function normalizeModelPreference(
  model: BuilderModelId | ModelPreference | undefined,
): ModelPreference | undefined {
  if (!model) return undefined;
  if (typeof model === 'string') return { preferred: model };
  return model;
}

/**
 * Render the `## Model` section for a charter, using the agent's model
 * preference or falling back to squad-level defaults.
 */
function renderModelSection(
  agentModel: BuilderModelId | ModelPreference | undefined,
  defaultModel: BuilderModelId | ModelPreference | undefined,
): string[] {
  const pref = normalizeModelPreference(agentModel) ?? normalizeModelPreference(defaultModel);
  if (!pref) return [];

  const lines: string[] = [];
  lines.push('## Model\n');
  lines.push(`**Preferred:** ${pref.preferred}`);
  if (pref.rationale) {
    lines.push(`**Rationale:** ${pref.rationale}`);
  }
  if (pref.fallback) {
    lines.push(`**Fallback:** ${pref.fallback}`);
  }
  lines.push('');
  return lines;
}

function generateCharterMd(agent: AgentDefinition, defaultModel?: BuilderModelId | ModelPreference): string {
  const lines: string[] = [GENERATED_HEADER];
  const name = agent.name;
  const role = agent.role;

  lines.push(`# ${name} — ${role}\n`);

  if (agent.description) {
    lines.push(`> ${agent.description}\n`);
  }

  if (agent.charter) {
    lines.push(agent.charter);
    lines.push('');
  }

  lines.push(...renderModelSection(agent.model, defaultModel));

  if (agent.tools && agent.tools.length > 0) {
    lines.push('## Tools\n');
    for (const t of agent.tools) {
      lines.push(`- ${t}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateCeremoniesMd(ceremonies: readonly CeremonyDefinition[]): string {
  const lines: string[] = [GENERATED_HEADER];

  lines.push('# Ceremonies\n');

  for (const c of ceremonies) {
    lines.push(`## ${c.name}`);
    if (c.schedule) lines.push(`**Schedule:** ${c.schedule}`);
    if (c.participants && c.participants.length > 0) {
      lines.push(`**Participants:** ${c.participants.join(', ')}`);
    }
    if (c.agenda) {
      lines.push('', c.agenda);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** Size threshold (bytes) above which ceremonies.md is split into dispatch table + skill files (#193). */
const CEREMONIES_SIZE_THRESHOLD = 15_000;

/**
 * Generate a compact dispatch table that stays well under the view-tool size limit.
 * Individual ceremony definitions live in skill files referenced by the table.
 */
function generateCeremoniesDispatchTable(ceremonies: readonly CeremonyDefinition[]): string {
  const lines: string[] = [GENERATED_HEADER];

  lines.push('# Ceremonies\n');
  lines.push('Ceremony definitions live in individual skill files. This table is the dispatch index.\n');
  lines.push('| Name | Trigger | Schedule | Participants | Skill |');
  lines.push('|------|---------|----------|--------------|-------|');

  for (const c of ceremonies) {
    const trigger = c.trigger ?? 'manual';
    const schedule = c.schedule ?? '—';
    const participants = c.participants?.join(', ') ?? '—';
    const slug = c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const skillPath = `.squad/skills/ceremony-${slug}/SKILL.md`;
    lines.push(`| ${c.name} | ${trigger} | ${schedule} | ${participants} | \`${skillPath}\` |`);
  }

  lines.push('');
  return lines.join('\n');
}

/** Generate an individual ceremony skill file. */
function generateCeremonySkillFile(c: CeremonyDefinition): string {
  const lines: string[] = [GENERATED_HEADER];

  lines.push(`# Ceremony: ${c.name}\n`);
  if (c.trigger) lines.push(`**Trigger:** ${c.trigger}`);
  if (c.schedule) lines.push(`**Schedule:** ${c.schedule}`);
  if (c.participants && c.participants.length > 0) {
    lines.push(`**Participants:** ${c.participants.join(', ')}`);
  }
  if (c.hooks && c.hooks.length > 0) {
    lines.push(`**Hooks:** ${c.hooks.join(', ')}`);
  }
  if (c.agenda) {
    lines.push('', c.agenda);
  }
  lines.push('');

  return lines.join('\n');
}

/** Generate a skill SKILL.md file from BuilderSkillDefinition. */
function generateSkillFile(skill: BuilderSkillDefinition): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push('---');
  lines.push(`name: "${skill.name}"`);
  lines.push(`description: "${skill.description}"`);
  lines.push(`domain: "${skill.domain}"`);
  if (skill.confidence) {
    lines.push(`confidence: "${skill.confidence}"`);
  }
  if (skill.source) {
    lines.push(`source: "${skill.source}"`);
  }
  if (skill.tools && skill.tools.length > 0) {
    lines.push('tools:');
    for (const tool of skill.tools) {
      lines.push(`  - name: "${tool.name}"`);
      lines.push(`    description: "${tool.description}"`);
      lines.push(`    when: "${tool.when}"`);
    }
  }
  lines.push('---');
  lines.push('');

  // Content
  lines.push(skill.content);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// File plan + writing
// ---------------------------------------------------------------------------

interface GeneratedFile {
  /** Relative path from project root (e.g. ".squad/team.md") */
  relPath: string;
  /** Generated content */
  content: string;
}

function buildFilePlan(config: SquadSDKConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // team.md
  files.push({
    relPath: '.squad/team.md',
    content: generateTeamMd(config),
  });

  // routing.md
  if (config.routing) {
    files.push({
      relPath: '.squad/routing.md',
      content: generateRoutingMd(config),
    });
  }

  // Agent charters
  const defaultModel = config.defaults?.model;
  for (const agent of config.agents) {
    files.push({
      relPath: `.squad/agents/${agent.name}/charter.md`,
      content: generateCharterMd(agent, defaultModel),
    });
  }

  // ceremonies.md — use dispatch table format when content exceeds size threshold (#193)
  if (config.ceremonies && config.ceremonies.length > 0) {
    const monolithic = generateCeremoniesMd(config.ceremonies);

    if (Buffer.byteLength(monolithic, 'utf-8') > CEREMONIES_SIZE_THRESHOLD) {
      // Large: emit dispatch table + individual skill files
      files.push({
        relPath: '.squad/ceremonies.md',
        content: generateCeremoniesDispatchTable(config.ceremonies),
      });
      for (const c of config.ceremonies) {
        const slug = c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
        files.push({
          relPath: `.squad/skills/ceremony-${slug}/SKILL.md`,
          content: generateCeremonySkillFile(c),
        });
      }
    } else {
      // Small: single monolithic file is fine
      files.push({
        relPath: '.squad/ceremonies.md',
        content: monolithic,
      });
    }
  }

  // skills — generate SKILL.md for each skill definition
  if (config.skills && config.skills.length > 0) {
    for (const skill of config.skills) {
      files.push({
        relPath: `.squad/skills/${skill.name}/SKILL.md`,
        content: generateSkillFile(skill),
      });
    }
  }

  return files;
}

function isProtected(relPath: string): boolean {
  const basename = path.basename(relPath);
  if (PROTECTED_FILES.has(basename)) return true;
  if (basename === 'history.md') return true;
  for (const dir of PROTECTED_DIRS) {
    if (relPath.includes(`/${dir}/`) || relPath.includes(`\\${dir}\\`)) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Core build actions
// ---------------------------------------------------------------------------

interface BuildResult {
  files: GeneratedFile[];
  written: number;
  skipped: number;
  drifted: string[];
}

function writeFiles(cwd: string, files: GeneratedFile[]): BuildResult {
  let written = 0;
  let skipped = 0;
  const drifted: string[] = [];

  for (const file of files) {
    if (isProtected(file.relPath)) {
      skipped++;
      continue;
    }

    const absPath = path.join(cwd, file.relPath);
    const dir = path.dirname(absPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(absPath, file.content, 'utf-8');
    written++;
  }

  return { files, written, skipped, drifted };
}

function checkDrift(cwd: string, files: GeneratedFile[]): { drifted: string[]; clean: string[] } {
  const drifted: string[] = [];
  const clean: string[] = [];

  for (const file of files) {
    if (isProtected(file.relPath)) continue;

    const absPath = path.join(cwd, file.relPath);
    if (!fs.existsSync(absPath)) {
      drifted.push(file.relPath);
      continue;
    }

    const existing = fs.readFileSync(absPath, 'utf-8');
    if (existing !== file.content) {
      drifted.push(file.relPath);
    } else {
      clean.push(file.relPath);
    }
  }

  return { drifted, clean };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface BuildOptions {
  check?: boolean;
  dryRun?: boolean;
  watch?: boolean;
}

/**
 * Run the squad build pipeline.
 *
 * @param cwd - Project root directory
 * @param options - CLI flags
 */
export async function runBuild(cwd: string, options: BuildOptions = {}): Promise<void> {
  // --watch stub
  if (options.watch) {
    info(`${YELLOW}⏳${RESET} Watch mode coming soon — rebuilding on file changes is not yet implemented.`);
    info(`   For now, run ${BOLD}squad build${RESET} manually after changes.`);
    return;
  }

  // Load config
  const { config, source } = await loadSquadConfig(cwd);
  dim(`  Config: ${path.relative(cwd, source) || source}`);

  // Build file plan
  const files = buildFilePlan(config);

  if (files.length === 0) {
    warn('Config produced no files to generate. Check your squad.config.ts.');
    return;
  }

  // --check mode
  if (options.check) {
    const { drifted, clean } = checkDrift(cwd, files);
    if (drifted.length === 0) {
      success(`All ${clean.length} generated files match disk — no drift detected.`);
      return;
    }

    console.log(`\n${RED}✗${RESET} ${BOLD}Drift detected${RESET} in ${drifted.length} file(s):\n`);
    for (const f of drifted) {
      console.log(`  ${RED}•${RESET} ${f}`);
    }
    console.log(`\n  Run ${BOLD}squad build${RESET} to regenerate.\n`);
    process.exit(1);
  }

  // --dry-run mode
  if (options.dryRun) {
    info(`\n${BOLD}Dry run${RESET} — would generate ${files.length} file(s):\n`);
    for (const file of files) {
      const exists = fs.existsSync(path.join(cwd, file.relPath));
      const label = exists ? `${YELLOW}overwrite${RESET}` : `${GREEN}create${RESET}`;
      console.log(`  ${label}  ${file.relPath}`);
    }
    console.log('');
    return;
  }

  // Default: write files
  const result = writeFiles(cwd, files);

  success(`squad build complete — generated ${result.written} file(s)`);
  if (result.skipped > 0) {
    dim(`  (${result.skipped} protected file(s) skipped)`);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function capitalize(str: string): string {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function formatStatus(status?: string): string {
  switch (status) {
    case 'active':
      return '✅ Active';
    case 'inactive':
      return '⏸️ Inactive';
    case 'retired':
      return '🔴 Retired';
    default:
      return '✅ Active';
  }
}
